Перлин Леонид
VK-BMSTU-QA/units-spring-2022 pull request #14
Opened 2022-03-17 18:40 UTC by perlinleo

2022-03-18 13:41 UTC, ThCompiler commented on src/utils/sortOrders.test.ts
> +	it('Count', () => {
случай получения с Date почему-то в соседнем describe

2022-03-18 13:41 UTC, ThCompiler commented on src/utils/sortOrders.test.ts
> +		expect(sortingFunc).toBeCalledTimes(2);
Думаю тут скорей подразумевалось проверить что он их отсортирует, как мы указали. по факту нигде нет проверки что функция умеет сортировать. плюс в зависимости от алгоритма сортировки функция сравнения вызовется разное число раз.

2022-03-18 13:48 UTC, ThCompiler approved these changes

2022-03-26 18:28 UTC, Betchika99 requested changes
неплохо, но немного замечаний есть. особое внимание удели названиям тестов

2022-03-26 18:28 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		const wrapper = shallow(<OrderComponent key={0} order={{
проп key не надо здесь передавать. key используется только при рендере массивов, чтобы показать реакту, что элементы отличаются и за их перерисовкой нужно следить по-разному. Если его не передать, реакт при изменении одного элемента будет считать, что поменялись все и все перерисует. При рендере одного компонента это не нужно. Здесь и далее

2022-03-26 18:28 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		const wrapper = shallow(<OrderComponent key={0} order={undefined} />);
это немного бессмысленный тест - этот кейс поймает TypeScript и линтер, т.к. по определению компонента он принимает в себя конкретный тип объекта https://github.com/VK-BMSTU-QA/units-spring-2022/blob/main/src/Order/Order.tsx#L7, т.е. undefined туда не попадет

2022-03-26 18:28 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
это бессмысленная проверка (посмотри снапшот, который получился), т.к. не информативна. лучше явно проверить, что вернулся null - expect(wrapper.getElement()).toBeNull()

2022-03-26 18:28 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +	it('Count', () => {
неинформативное название. посмотри нейминги тестов повнимательнее

2022-03-26 18:28 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +		sortOrders(unsortedOrders, sortByDate);
в таком случае выглядит, будто два теста в одном - ты тестишь больше sortByDate функцию, чем sortOrders. А это нарушает принципы автоматизации тестирования

2022-03-26 18:28 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +	test.each([
семантически эти тесты всё-таки разные. если, например, мы решим при какой-то определенной сортировке возвращать не 0, а null, придётся вчитываться в этот тест, чтобы понять, что менять. циклы чаще используются, когда входные данные +- одинаковые, а выходные одинаковые (например, классы эквивалентности). в остальных кейсах, особенно в разных по логике, нужно писать отдельные кейсы

2022-03-26 18:28 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +	])('.sortByItemCount(%s, %s)', ({ a, b, expected }) => {
плохо считывается название теста тоже =(

2022-03-26 18:28 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +describe('sortByDateCount function', () => {
аналогичная проблема с циклом

2022-03-28 19:36 UTC, closed without merging