Кучерявенко Алексей
VK-BMSTU-QA/units-spring-2022 pull request #16
Opened 2022-03-17 18:52 UTC by frbgd

2022-03-17 19:20 UTC, Shureks-den requested changes

2022-03-17 19:20 UTC, Shureks-den commented on src/Order/Order.test.tsx
> +		jest.resetModules();
Выглядит немного избыточно, когда есть clearAllMocks()

2022-03-17 19:20 UTC, Shureks-den commented on src/Order/Order.test.tsx
> +	it('order with empty items', () => {
Два одинаковых описания, сложно понять чем тестыотличаются

2022-03-17 19:20 UTC, Shureks-den commented on src/Order/Order.test.tsx
> +	it('order with null items', () => {
Тут все таки items не null, а пустой массив

2022-03-17 19:20 UTC, Shureks-den commented on src/Order/Order.test.tsx
> +	it('order with null items', () => {
Кажется в fakeOrders[0] items и так пустой массив

2022-03-18 08:48 UTC, 23-yo-designer-from-san-francisco approved these changes

2022-03-18 09:47 UTC, Shureks-den approved these changes

2022-03-24 16:00 UTC, VictoriaOtm commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
пустой снэп

2022-03-24 16:02 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +		expect(sortOrders(orders, sortByItemCount)).toBe(undefined);
нужно проверять вызов sortFunction

2022-03-26 11:24 UTC, closed without merging