Ширшов Артём Тесты
VK-BMSTU-QA/units-spring-2022 pull request #17
Opened 2022-03-17 18:54 UTC by a-shirshov

2022-03-17 20:25 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +describe('sortByItemCount function', () => {
describe - для одного юнита
it - для одного тесткейса

2022-03-17 20:25 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +		expect(result).toBe(null);
можно использовать toBeNull(), по смыслу то же самое, но вывод красивее)

2022-03-17 20:25 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +*/
коменты чистим

2022-03-17 20:25 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +
по заданию, надо было сделать тесты для всех функций из sortOrders.tsx.
не вижу теста для функции sortOrders.

2022-03-18 10:32 UTC, comradyo approved these changes

2022-03-18 10:33 UTC, comradyo commented on src/Order/Order.test.tsx
> +	it('order', () => {
Отмена аппрува

2022-03-18 10:37 UTC, comradyo requested changes

2022-03-18 10:37 UTC, comradyo commented on src/Order/Order.test.tsx
>  	});
Стоит протестировать случай, когда order = {} (случайно аппрувнул)

2022-03-18 10:37 UTC, comradyo commented on src/Order/Order.test.tsx
> +	it('order', () => {
Думаю, стоит более понятное название дать (normal order, например) (случайно аппрувнул)

2022-03-18 10:37 UTC, comradyo commented on src/utils/sortOrders.test.ts
> +});
В describe пишешь название тестируемой функции (и что именно тестируешь, не обязательно всю функцию), в it - название кейса в рамках данного набора тестов (случайно аппрувнул)

2022-03-18 10:37 UTC, comradyo commented on src/utils/sortOrders.test.ts
> +		expect(result).toBe(null);
переделай в toBeNull() (случайно аппрувнул)

2022-03-18 10:37 UTC, comradyo commented on src/utils/sortOrders.test.ts
> +*/
удали комментарии (случайно аппрувнул)

2022-03-18 10:37 UTC, comradyo commented on src/utils/sortOrders.test.ts
> +
нет тестов на sortOrders (случайно аппрувнул)

2022-03-18 14:41 UTC, just4n4cc approved these changes
другое дело, парень

2022-03-26 18:15 UTC, Betchika99 requested changes
неплохие тесты. немного замечаний, чтобы сделать твои тесты еще круче :)

2022-03-26 18:15 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		getDate.mockReturnValue('1 января, чт, 1970 год');
давай вынесем это в beforeEach хук, чтобы не делать дубль в каждом тесте

2022-03-26 18:15 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		wrapper = shallow(<OrderComponent key = {key} order = {order}/>);
проп key не надо здесь передавать. key используется только при рендере массивов, чтобы показать реакту, что элементы отличаются и за их перерисовкой нужно следить по-разному. Если его не передать, реакт при изменении одного элемента будет считать, что поменялись все и все перерисует. При рендере одного компонента это не нужно. Здесь и далее

2022-03-26 18:15 UTC, Betchika99 commented on src/Order/Order.test.tsx
>  });
нет очистки моков после прохождения тестов

2022-03-26 18:15 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
это бессмысленная проверка (посмотри снапшот, который получился), т.к. не информативна. лучше явно проверить, что вернулся null  - expect(wrapper.getElement()).toBeNull()

2022-03-26 18:15 UTC, Betchika99 commented on src/Order/Order.test.tsx
> +		expect(wrapper).toMatchSnapshot();
аналогично "no date" тесту - это бессмысленная проверка

2022-03-26 18:15 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +});
нет позитивных кейсов

2022-03-26 18:15 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +});
не все кейсы покрыты

2022-03-26 23:32 UTC, closed without merging