PR: Седойкин Георгий
VK-BMSTU-QA/units-spring-2022 pull request #19
Opened 2022-03-17 19:14 UTC by GeorgiyX

2022-03-18 07:30 UTC, TonyBlock approved these changes
Лайк

2022-03-18 11:22 UTC, DPeshkoff requested changes
Привет, мне нравится (отдельный лайк за комментарии)
Накинул немного вопросиков:

2022-03-18 11:22 UTC, DPeshkoff commented on src/utils/sortOrders.test.ts
> +	it('wong type', () => {
```suggestion
	it('wrong type', () => {
```

2022-03-18 11:22 UTC, DPeshkoff commented on src/utils/sortOrders.test.ts
> +});
Мне кажется, что этот тест проверяет работу скорее сортировочной функции, чем `sortOrders`

Не уверен, что это полезно - если упадет сортировочная функция, то и этот тест упадет, хотя сама функция продолжит корректно работать

2022-03-18 12:00 UTC, GeorgiyX commented on src/utils/sortOrders.test.ts
> +});
Да, справедливое замечание

2022-03-18 14:09 UTC, DPeshkoff approved these changes
Искра, буря, аппрув)

2022-03-26 17:29 UTC, VictoriaOtm commented on src/Order/__snapshots__/Order.test.tsx.snap
> +exports[`Order.tsx test name: null data 1`] = `""`;
не стоит записывать пустой снапшот, от него мало пользы, можно делать expect(wrapper.getElement()).toBeNull()

2022-04-01 11:53 UTC, closed without merging