Семинар по unit тестированию
VK-BMSTU-QA/units-spring-2022 pull request #2
Opened 2022-03-17 18:00 UTC by Flash1ee

2022-03-17 20:28 UTC, VolodyaLarin requested changes

2022-03-18 13:08 UTC, perlinleo approved these changes

2022-03-18 14:35 UTC, Flash1ee commented on src/utils/sortOrders.test.ts
> +	sortByItemCount,
Если упадут тесты на ту функцию, то и на это упадут, да, именно так. Раз в функции есть описание и использование компараторов, то думаю их стоит использовать, а если она сломается, то этот тест тоже должен сломаться, раз он зависит от конкретной функции, а не от абстрактной

2022-03-18 14:35 UTC, Flash1ee commented on src/utils/sortOrders.test.ts
> +])('sortByItemCount(%i, %i, %i)', (a, b, expected) => {
Это табличный тест, если упадет, увидишь аргументы, с которыми он запустился, они простые -> самодокументируемы

2022-03-18 14:50 UTC, VolodyaLarin approved these changes

2022-03-21 16:13 UTC, VictoriaOtm commented on src/Order/Order.test.tsx
> +			const order = fakeOrders[0];
но все-таки лучше писать более понятное название каждого тесткейса, по типу "Что должно делать, с какими данными"

2022-03-21 16:14 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +])('sortByItemCount(%i, %i, %i)', (a, b, expected) => {
да, он табличный, но заслуживает быть помещенным в describe, чтобы n тестов объединились в тестовый набор)

2022-03-21 16:15 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +test.each([
и тут describe

2022-03-21 16:15 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +test.each([
и ниже

2022-03-22 07:45 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +it('stable sort', () => {
что-то не согласна с твоим разделением на тестовые наборы и тесткейсы, разнесение одной и той же функции по разным тестовым наборам сильно путает, принято делать как:
describe('метод sortByDate', () => {<все тесткейсы по sortByDate>})
describe('метод sortByCount', () => {<все тесткейсы по sortByCount>})

а тут немного намешано, структура рушится, читаемость ухудшается, появляются лишние тесткейсы

2022-03-22 08:10 UTC, VictoriaOtm commented on src/Order/Order.test.tsx
> +			const orderComponent = OrderComponent({order: order});
ты не делаешь ни shallow, ни mount, почему? рекомендую почитать про них https://medium.com/@aminebenkeroum/enzyme-understand-render-mount-and-shallow-6b2a7ee9a7

2022-03-22 19:57 UTC, Flash1ee commented on src/Order/Order.test.tsx
> +			const orderComponent = OrderComponent({order: order});
Добавил shallow

2022-03-22 20:00 UTC, Flash1ee reviewed
resolve review notes

2022-03-26 17:17 UTC, VictoriaOtm commented on src/Order/__snapshots__/Order.test.tsx.snap
> +exports[`Order.tsx Order.tsx OrderComponent({order: { date: undefined, shop: 'amazon', items: [Array] }}) 1`] = `""`;
не нужно записывать пустой снапшот, wrapper.getElement() можно сравнивать с null

2022-03-26 17:18 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +describe('sortByItemCount invalid', () => {
а зачем sortByItemCount invalid выносить в отдельный тестовый набор? почему эти it нельзя написать в describe выше? к тому же там у тебя уже есть негативные кейсы, это лишнее

2022-03-26 17:19 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +describe('sortByDate invalid', () => {
аналогично

2022-03-26 17:21 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +		expect(orders).toEqual(expected);
в sortOrders не нужно проверять то, как отсортируется массив, ты это делаешь, тестируя sortByDate и sortByItemCount, тестируя sortOrders таким образом ты проверяшь нативный js sort, это лишнее. Здесь достаточно проверить, что передаваемые методы вызываются, то, что нужно, возвращается

2022-03-26 17:21 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +describe('sortByDate tests', () => {
так есть же уже тесты на sortByItemCount

2022-03-26 17:22 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +describe('sortByItemCount tests', () => {
?

2022-03-26 18:15 UTC, Flash1ee commented on src/utils/sortOrders.test.ts
> +describe('sortByItemCount invalid', () => {
Я в этом случае явно подаю на вход Nan, а выше Nan - это items. Разные проверки

2022-03-28 13:29 UTC, VictoriaOtm commented on src/utils/sortOrders.test.ts
> +		expect(orders).toEqual(sortedOrders);
а какой смысл в этом ассерте?)

2022-03-28 14:15 UTC, closed without merging