Никитина Ксения
VK-BMSTU-QA/units-spring-2022 pull request #5
Opened 2022-03-17 18:07 UTC by zdesbilaksenia

2022-03-17 20:12 UTC, just4n4cc reviewed
поправь и апрувну мб)

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +	])('sort items with orders', ({first, second, expected}) => {
orders with items!

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +	it('sort items with empty orders', () => {
туда же

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +	])('sort items without date', ({first, second, expected}) => {
вот будут смотреть тесты и не поймет никто, что за тест такой..

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +	it('sort items with empty orders', () => {
(

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.test.ts
> +	it('sort items by date', () => {
последний вроде

2022-03-17 20:12 UTC, just4n4cc commented on src/utils/sortOrders.ts
> -
я понимаю зачем, но так можно было?

2022-03-17 20:12 UTC, just4n4cc commented on src/Order/Order.test.tsx
> +		getDate.mockReturnValue('date');
В моем понимании мок должен эмулировать поведение исходного объекта, а тут возвращаемое значение, которое реальная функция никогда бы не вернула. 
Конечно на результат это не влияет, но ,как следствие, имеем неправильные снапшоты, относительно исходных данных ордеров.
Я бы поправил на дату, которая должна получаться для каждого отдельного теста.

2022-03-18 10:31 UTC, comradyo requested changes
сделал ревью

2022-03-18 11:16 UTC, zdesbilaksenia commented on src/Order/Order.test.tsx
> +		getDate.mockReturnValue('date');
снапшоты вроде необязательно должны быть прям реалистичными, к тому же это ни на что не влияет, а beforeEach выглядит покрасивее(

2022-03-18 11:45 UTC, comradyo approved these changes
апрувнул

2022-03-18 14:36 UTC, just4n4cc approved these changes

2022-03-25 20:11 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +	test.each([
аналогично - лучше не объединять в цикл

2022-03-31 11:55 UTC, closed without merging