Новикова Марина
VK-BMSTU-QA/units-spring-2022 pull request #7
Opened 2022-03-17 18:17 UTC by fillinmar

2022-03-17 18:53 UTC, VolodyaLarin commented
Привет, я буду тебя менторить. 

Ты победила в рандом соревновании))
![изображение](https://user-images.githubusercontent.com/12639263/158875143-c08d358a-b261-4ac8-acc9-33f1a0cd8cb0.png)

2022-03-17 20:27 UTC, VolodyaLarin requested changes
Если, что напомню ТГ https://t.me/volodyalarin

2022-03-18 08:35 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +		sortOrders(fakeOrders, sortByDate);
я эту функцию выше протестила, как по твоему мнению, ее тогда можно протестить?

2022-03-18 08:42 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +	});
эта же как раз тест, когда заказы уже сортированы

2022-03-18 08:47 UTC, fillinmar commented on src/Order/Order.test.tsx
> +		expect(getDate).toBeCalled();
хмм, оки разделю спасибо

2022-03-18 09:38 UTC, VolodyaLarin commented on src/utils/sortOrders.test.ts
> +		sortOrders(fakeOrders, sortByDate);
Например, написать ф-цию сравнения, используемую только для тестов, или замокать уже имеющуюся ф-цию.

Но так как  в данном случае это выглядит избыточным, то давай оставим всё как есть.

2022-03-18 10:15 UTC, tr0llex approved these changes
Молодец, хорошо поработала! Жаль, у меня не получилось ;(

2022-03-18 10:31 UTC, Shureks-den requested changes

2022-03-18 10:31 UTC, Shureks-den commented on src/utils/sortOrders.test.ts
> +describe('sortByDate function', () => {
Можно заметить, что sortByDate аналогично sortByItemsCount принимает 
<img width="227" alt="image" src="https://user-images.githubusercontent.com/65308659/158986996-828c4c99-e85c-4f9a-8188-d9f6f4beb3a8.png">
И поэтому, имхо, можно убрать ненужные поля в объектах в тестах

2022-03-18 10:46 UTC, Shureks-den approved these changes

2022-03-18 10:50 UTC, VolodyaLarin approved these changes

2022-03-25 22:07 UTC, Betchika99 requested changes
неплохие тесты, молодец. но где-то намешана логика, что делает тесты чуть хуже читаемыми. и еще некоторые замечания

2022-03-25 22:07 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +		sortOrders(fakeOrders, sortByDate);
в данном случае согласна с Владимиром. мы должны писать независимые и автономные тесты. Если завтра кто-то удалит тест на sortByDate, то мы никогда не узнаем, что она сломалась, а этот тест будет падать, хотя к ней совсем отношения не имеет

2022-03-25 22:07 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +		const sortedFakeOrders: Order[] = [
зачем еще одна переменная, если значение  такое же, как у fakeOrders?

2022-03-25 22:07 UTC, Betchika99 commented on src/utils/sortOrders.test.ts
> +describe('sortOrders function', () => {
посмотри внимательно на тесты в этой кейсе. кажется, в некоторых из них проверяется не работа функции sortOrders, а работа функции sortByItemCount/sortByDate, т.е. два теста в одном. сами функции сортировки уже протестированы отдельно

2022-03-27 20:16 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +	]) ('%p', (name, firstOrder, secondOrder, expected) => {
поняла, спасибо боольшое

2022-03-27 20:17 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +	it.each([
поправила

2022-03-27 20:21 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +	it.each([
поправила

2022-03-27 20:22 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +	it('sort order by date', () => {
поправила

2022-03-27 20:45 UTC, fillinmar commented on src/utils/sortOrders.test.ts
> +describe('sortOrders function', () => {
логично, спасибо, поправила

2022-03-27 21:08 UTC, closed without merging